# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: login_auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'login_auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10login_auth.proto\x12\x05login\"3\n\x0cLoginRequest\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x12\n\ncontrasena\x18\x02 \x01(\t\"/\n\rLoginResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"0\n\rCodigoRequest\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x0e\n\x06\x63odigo\x18\x02 \x01(\t\"0\n\x0e\x43odigoResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2\x82\x01\n\x0cLoginService\x12\x32\n\x05Login\x12\x13.login.LoginRequest\x1a\x14.login.LoginResponse\x12>\n\x0fVerificarCodigo\x12\x14.login.CodigoRequest\x1a\x15.login.CodigoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=27
  _globals['_LOGINREQUEST']._serialized_end=78
  _globals['_LOGINRESPONSE']._serialized_start=80
  _globals['_LOGINRESPONSE']._serialized_end=127
  _globals['_CODIGOREQUEST']._serialized_start=129
  _globals['_CODIGOREQUEST']._serialized_end=177
  _globals['_CODIGORESPONSE']._serialized_start=179
  _globals['_CODIGORESPONSE']._serialized_end=227
  _globals['_LOGINSERVICE']._serialized_start=230
  _globals['_LOGINSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
