# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from generate import login_auth_pb2 as login__auth__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in login_auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoginServiceStub(object):
    """Servicio principal de login
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/login.LoginService/Login',
                request_serializer=login__auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=login__auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.VerificarCodigo = channel.unary_unary(
                '/login.LoginService/VerificarCodigo',
                request_serializer=login__auth__pb2.CodigoRequest.SerializeToString,
                response_deserializer=login__auth__pb2.CodigoResponse.FromString,
                _registered_method=True)


class LoginServiceServicer(object):
    """Servicio principal de login
    """

    def Login(self, request, context):
        """Paso 1: Enviar usuario y contraseña
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerificarCodigo(self, request, context):
        """Paso 2: Verificar código 2FA
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=login__auth__pb2.LoginRequest.FromString,
                    response_serializer=login__auth__pb2.LoginResponse.SerializeToString,
            ),
            'VerificarCodigo': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarCodigo,
                    request_deserializer=login__auth__pb2.CodigoRequest.FromString,
                    response_serializer=login__auth__pb2.CodigoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'login.LoginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('login.LoginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoginService(object):
    """Servicio principal de login
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/login.LoginService/Login',
            login__auth__pb2.LoginRequest.SerializeToString,
            login__auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerificarCodigo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/login.LoginService/VerificarCodigo',
            login__auth__pb2.CodigoRequest.SerializeToString,
            login__auth__pb2.CodigoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
